import { Item } from '@/types/game';

export const BASE_CARD_POOL: Omit<Item, 'id'>[] = [
  {
    type: 'coin',
    name: 'Münze',
    icon: '🪙',
    description: 'Basis 1. Wert verdoppelt sich (x2), wenn angrenzend an Münze oder Sammler.',
    baseValue: 1,
    tier: 1,
  },
  {
    type: 'sprout',
    name: 'Keimling',
    icon: '🌱',
    description: 'Basis 1. Wächst +1/Zug bei 1+ freiem Nachbarn. Explodiert bei Zerstörung für doppelten Wert.',
    baseValue: 1,
    tier: 1,
  },
  {
    type: 'compass',
    name: 'Kompass',
    icon: '🧭',
    description: 'Basis 2. Verdoppelt (x2) an Kanten/Ecken die Punktwerte aller angrenzenden Nachbarn.',
    baseValue: 2,
    tier: 1,
  },
  {
    type: 'crystal',
    name: 'Resonanz-Kristall',
    icon: '❇️',
    description: 'Basis 1. Erhält +2 Punkte für JEDE Karte des am häufigsten vertretenen Kartentyps auf dem Board.',
    baseValue: 1,
    tier: 1,
  },
];

export const INITIAL_DECK = BASE_CARD_POOL;

export const CATALOG_POOL: Omit<Item, 'id'>[] = [
  // --- TIER 1 (Starter) ---
  {
    type: 'coin',
    name: 'Münze',
    icon: '🪙',
    description: 'Basis 1. Wert verdoppelt sich (x2), wenn angrenzend an Münze oder Sammler.',
    baseValue: 1,
    tier: 1,
  },
  {
    type: 'sprout',
    name: 'Keimling',
    icon: '🌱',
    description: 'Basis 1. Wächst +1/Zug bei 1+ freiem Nachbarn. Explodiert bei Zerstörung für doppelten Wert.',
    baseValue: 1,
    tier: 1,
  },
  {
    type: 'compass',
    name: 'Kompass',
    icon: '🧭',
    description: 'Basis 2. Verdoppelt (x2) an Kanten/Ecken die Punktwerte aller angrenzenden Nachbarn.',
    baseValue: 2,
    tier: 1,
  },
  {
    type: 'crystal',
    name: 'Resonanz-Kristall',
    icon: '❇️',
    description: 'Basis 1. Erhält +2 Punkte für JEDE Karte des am häufigsten vertretenen Kartentyps auf dem Board.',
    baseValue: 1,
    tier: 1,
  },

  // --- TIER 2 (Synergie-Starter) ---
  {
    type: 'vulture',
    name: 'Aasgeier',
    icon: '🦅',
    description: 'Erhält dauerhaft +4 Punkte für JEDE Karte auf dem Board, die zerstört, aufgesaugt oder entfernt wird.',
    baseValue: 0,
    tier: 2,
  },
  {
    type: 'hermit',
    name: 'Einsiedler',
    icon: '🧗',
    description: 'Erhält +3 Punkte für JEDE leere Kachel auf dem gesamten Board. Darf keine direkten Nachbarn haben.',
    baseValue: 0,
    tier: 2,
  },
  {
    type: 'collector',
    name: 'Sammler',
    icon: '👛',
    description: 'Basis +1 (+2 pro Münze auf Board). Ertrag verdoppelt (x2) bei 3+ Münzen.',
    baseValue: 1,
    tier: 2,
  },
  {
    type: 'orb',
    name: 'Glaskugel',
    icon: '🔮',
    description: 'Basis 2. Multipliziert den Ertrag aller angrenzenden Tier-1 Standard-Karten mit x2.',
    baseValue: 2,
    tier: 2,
  },
  {
    type: 'amplifier',
    name: 'Verstärker',
    icon: '⚡',
    description: 'Basis 2. Gibt allen direkt angrenzenden Nachbarkarten +5 Bonus-Ertrag.',
    baseValue: 2,
    tier: 2,
  },
  {
    type: 'pyre',
    name: 'Scheiterhaufen',
    icon: '🔥',
    description: 'Zerstört bei Platzierung sich selbst & alle 4 Nachbarn (+6 Punkte pro Karte).',
    baseValue: 0,
    tier: 2,
  },
  {
    type: 'recycler',
    name: 'Recycler',
    icon: '♻️',
    description: 'Zerstört angrenzende Karte mit niedrigstem Wert (+doppelter Basiswert als Ertrag).',
    baseValue: 1,
    tier: 2,
  },
  {
    type: 'smith',
    name: 'Schmied',
    icon: '🔨',
    description: 'Wandelt bei Platzierung angrenzende Tier 1 Items in Goldschätze (+4) um.',
    baseValue: 1,
    tier: 2,
  },

  // --- TIER 3 (Multiplikatoren) ---
  {
    type: 'catalyst',
    name: 'Katalysator',
    icon: '🧪',
    description: 'Basis 2. Verdoppelt (x2) den Endwert aller Karten in derselben Reihe.',
    baseValue: 2,
    tier: 3,
  },
  {
    type: 'magnet',
    name: 'Magnet',
    icon: '🧲',
    description: 'Saugt Basiswerte der 4 Nachbarn ab & verdreifacht (x3) seinen eigenen Gesamtwert.',
    baseValue: 2,
    tier: 3,
  },
  {
    type: 'demolition_ball',
    name: 'Abrissbirne',
    icon: '🏗️',
    description: 'Zerstört die gesamte Reihe (+10 Punkte & Keimling-Bonus pro zerstörter Karte).',
    baseValue: 0,
    tier: 3,
  },
  {
    type: 'mosaic',
    name: 'Mosaik',
    icon: '🧩',
    description: '+4 pro einzigartigem Kartentyp auf dem Board.',
    baseValue: 0,
    tier: 3,
  },
  {
    type: 'vacuum',
    name: 'Vakuum',
    icon: '🌪️',
    description: '+4 pro LEEREM Feld auf dem 4x4-Board.',
    baseValue: 0,
    tier: 3,
  },

  // --- TIER 4 (Board-weite Skalierung) ---
  {
    type: 'vault',
    name: 'Tresor',
    icon: '🏛️',
    description: 'Gibt +15 Punkte für jede Karte im Deck und x2 auf das aktuelle Feld.',
    baseValue: 0,
    tier: 4,
  },
  {
    type: 'supernova',
    name: 'Supernova',
    icon: '💥',
    description: 'Zerstört bei Platzierung ALLE Tier-1 Karten auf dem Board (+25 Punkte pro Karte).',
    baseValue: 0,
    tier: 4,
  },
  {
    type: 'compressor',
    name: 'Verdichter',
    icon: '🌀',
    description: 'Absorbiert 4 Nachbarn und verdoppelt (x2) seinen eigenen Wert pro gefressener Karte.',
    baseValue: 0,
    tier: 4,
  },
  {
    type: 'midas',
    name: 'Midas',
    icon: '👑',
    description: 'Verdoppelt Basiswerte der Nachbarn & +5 Punkte pro Münze.',
    baseValue: 1,
    tier: 4,
  },
  {
    type: 'prism',
    name: 'Prisma',
    icon: '💎',
    description: 'Erhöht den aus allen Kacheln berechneten Gesamt-Score am Ende um x1.5 (+50%).',
    baseValue: 0,
    tier: 4,
  },

  // --- TIER 5 (God-Mode / Win-Conditions) ---
  {
    type: 'philosopher_stone',
    name: 'Der Stein der Weisen',
    icon: '🪐',
    description: 'GOD-MODE: Multipliziert den FINAL-SCORE der gesamten Runde mit x3!',
    baseValue: 5,
    tier: 5,
  },
  {
    type: 'world_tree',
    name: 'Weltenbaum',
    icon: '🌳',
    description: 'GOD-MODE: Erhält +10 Punkte für JEDE besetzte Kachel auf dem gesamten Board!',
    baseValue: 10,
    tier: 5,
  },
  {
    type: 'singularity',
    name: 'Singularität',
    icon: '🕳️',
    description: 'Generiert +15 Basis-Ertrag & frisst am Zugende angrenzende Karten für Bonus.',
    baseValue: 15,
    tier: 5,
  },
];
