import { Item } from '@/types/game';

export const BASE_CARD_POOL: Omit<Item, 'id'>[] = [
  {
    type: 'coin',
    name: 'Münze',
    icon: '🪙',
    description: 'Basis 1 Feldwert. Feldwert verdoppelt sich (x2), wenn angrenzend an Münze oder Sammler.',
    baseValue: 1,
    tier: 1,
  },
  {
    type: 'sprout',
    name: 'Keimling',
    icon: '🌱',
    description: 'Basis 1. Wächst +1/Zug auf Feldwert bei 1+ freiem Nachbarn. Explodiert bei Zerstörung für doppelten Wert als Sofort-Punkte.',
    baseValue: 1,
    tier: 1,
  },
  {
    type: 'compass',
    name: 'Kompass',
    icon: '🧭',
    description: 'Basis 2 Feldwert. Verdoppelt (x2) an Kanten/Ecken die Feldwerte aller angrenzenden Nachbarn.',
    baseValue: 2,
    tier: 1,
  },
  {
    type: 'crystal',
    name: 'Resonanz-Kristall',
    icon: '❇️',
    description: 'Basis 1. Erhält +2 auf den Feldwert für JEDE Karte des am häufigsten vertretenen Kartentyps auf dem Board.',
    baseValue: 1,
    tier: 1,
  },
];

export const INITIAL_DECK = BASE_CARD_POOL;

export const CATALOG_POOL: Omit<Item, 'id'>[] = [
  // --- TIER 1 (Starter) ---
  {
    type: 'coin',
    name: 'Münze',
    icon: '🪙',
    description: 'Basis 1 Feldwert. Feldwert verdoppelt sich (x2), wenn angrenzend an Münze oder Sammler.',
    baseValue: 1,
    tier: 1,
  },
  {
    type: 'sprout',
    name: 'Keimling',
    icon: '🌱',
    description: 'Basis 1. Wächst +1/Zug auf Feldwert bei 1+ freiem Nachbarn. Explodiert bei Zerstörung für doppelten Wert als Sofort-Punkte.',
    baseValue: 1,
    tier: 1,
  },
  {
    type: 'compass',
    name: 'Kompass',
    icon: '🧭',
    description: 'Basis 2 Feldwert. Verdoppelt (x2) an Kanten/Ecken die Feldwerte aller angrenzenden Nachbarn.',
    baseValue: 2,
    tier: 1,
  },
  {
    type: 'crystal',
    name: 'Resonanz-Kristall',
    icon: '❇️',
    description: 'Basis 1. Erhält +2 auf den Feldwert für JEDE Karte des am häufigsten vertretenen Kartentyps auf dem Board.',
    baseValue: 1,
    tier: 1,
  },

  // --- TIER 2 (Synergie-Starter) ---
  {
    type: 'vulture',
    name: 'Aasgeier',
    icon: '🦅',
    description: 'Erhält dauerhaft +4 auf den Feldwert für JEDE Karte auf dem Board, die zerstört, aufgesaugt oder entfernt wird.',
    baseValue: 0,
    tier: 2,
  },
  {
    type: 'hermit',
    name: 'Einsiedler',
    icon: '🧗',
    description: 'Erhält +3 auf den Feldwert für JEDE leere Kachel auf dem Board. Darf keine direkten Nachbarn haben.',
    baseValue: 0,
    tier: 2,
  },
  {
    type: 'collector',
    name: 'Sammler',
    icon: '👛',
    description: 'Basis 1 (+2 pro Münze auf Board auf den Feldwert). Feldwert verdoppelt (x2) bei 3+ Münzen.',
    baseValue: 1,
    tier: 2,
  },
  {
    type: 'orb',
    name: 'Glaskugel',
    icon: '🔮',
    description: 'Basis 2 Feldwert. Multipliziert den Feldwert aller angrenzenden Tier-1 Standard-Karten mit x2.',
    baseValue: 2,
    tier: 2,
  },
  {
    type: 'amplifier',
    name: 'Verstärker',
    icon: '⚡',
    description: 'Basis 2 Feldwert. Gibt allen direkt angrenzenden Nachbarkarten +5 auf den Feldwert.',
    baseValue: 2,
    tier: 2,
  },
  {
    type: 'pyre',
    name: 'Scheiterhaufen',
    icon: '🔥',
    description: 'Zerstört bei Platzierung sich selbst & alle 4 Nachbarn (+6 Sofort-Punkte pro zerstörter Karte).',
    baseValue: 0,
    tier: 2,
  },
  {
    type: 'recycler',
    name: 'Recycler',
    icon: '♻️',
    description: 'Zerstört angrenzende Karte mit niedrigstem Wert (+doppelter Basiswert als Sofort-Punkte).',
    baseValue: 1,
    tier: 2,
  },
  {
    type: 'smith',
    name: 'Schmied',
    icon: '🔨',
    description: 'Wandelt bei Platzierung angrenzende Tier 1 Items in Goldschätze (+4 Feldwert) um.',
    baseValue: 1,
    tier: 2,
  },

  // --- TIER 3 (Multiplikatoren) ---
  {
    type: 'catalyst',
    name: 'Katalysator',
    icon: '🧪',
    description: 'Basis 2 Feldwert. Verdoppelt (x2) den Feldwert aller Karten in derselben Reihe.',
    baseValue: 2,
    tier: 3,
  },
  {
    type: 'magnet',
    name: 'Magnet',
    icon: '🧲',
    description: 'Saugt Basiswerte der 4 Nachbarn ab & verdreifacht (x3) seinen eigenen Feldwert.',
    baseValue: 2,
    tier: 3,
  },
  {
    type: 'demolition_ball',
    name: 'Abrissbirne',
    icon: '🏗️',
    description: 'Zerstört die gesamte Reihe (+10 Sofort-Punkte & Keimling-Bonus pro zerstörter Karte).',
    baseValue: 0,
    tier: 3,
  },
  {
    type: 'mosaic',
    name: 'Mosaik',
    icon: '🧩',
    description: '+4 auf den Feldwert pro einzigartigem Kartentyp auf dem Board.',
    baseValue: 0,
    tier: 3,
  },
  {
    type: 'vacuum',
    name: 'Vakuum',
    icon: '🌪️',
    description: '+4 auf den Feldwert pro LEEREM Feld auf dem Board.',
    baseValue: 0,
    tier: 3,
  },

  // --- TIER 4 (Board-weite Skalierung) ---
  {
    type: 'vault',
    name: 'Tresor',
    icon: '🏛️',
    description: 'Gibt +15 auf den Feldwert für jede Karte im Deck und x2 auf das eigene Feld.',
    baseValue: 0,
    tier: 4,
  },
  {
    type: 'supernova',
    name: 'Supernova',
    icon: '💥',
    description: 'Zerstört bei Platzierung ALLE Tier-1 Karten auf dem Board (+25 Sofort-Punkte pro Karte).',
    baseValue: 0,
    tier: 4,
  },
  {
    type: 'compressor',
    name: 'Verdichter',
    icon: '🌀',
    description: 'Absorbiert 4 Nachbarn und verdoppelt (x2) den gefressenen Wert als Feldwert.',
    baseValue: 0,
    tier: 4,
  },
  {
    type: 'midas',
    name: 'Midas',
    icon: '👑',
    description: 'Verdoppelt Basiswerte der Nachbarn & +5 auf den Feldwert pro Münze.',
    baseValue: 1,
    tier: 4,
  },
  {
    type: 'prism',
    name: 'Prisma',
    icon: '💎',
    description: 'Erhöht den aus allen Kacheln berechneten Gesamt-Board-Wert am Ende um x1.5 (+50%).',
    baseValue: 0,
    tier: 4,
  },

  // --- TIER 5 (God-Mode / Win-Conditions) ---
  {
    type: 'philosopher_stone',
    name: 'Der Stein der Weisen',
    icon: '🪐',
    description: 'GOD-MODE: Multipliziert den RUNDEN-FINALSCORE (Board + Sofort) mit x3!',
    baseValue: 5,
    tier: 5,
  },
  {
    type: 'world_tree',
    name: 'Weltenbaum',
    icon: '🌳',
    description: 'GOD-MODE: Erhält +10 auf den Feldwert für JEDE besetzte Kachel auf dem Board!',
    baseValue: 10,
    tier: 5,
  },
  {
    type: 'singularity',
    name: 'Singularität',
    icon: '🕳️',
    description: 'Generiert +15 Feldwert & frisst am Zugende angrenzende Karten für Sofort-Punkte.',
    baseValue: 15,
    tier: 5,
  },
];
